# Generated by Django 3.0.6 on 2020-06-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SAMLConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=64)),
                ('entity_id', models.CharField(max_length=256)),
                ('certificate', models.CharField(max_length=4096)),
            ],
        ),
    ]
